-- ServiceLink baseline schema (V1).
--
-- Generated from the JPA entities by booting Hibernate with ddl-auto=create
-- against a clean Postgres 16 and dumping the result, rather than hand-written:
-- the Envers audit tables (ticket_aud, service_link_revision) and the identity
-- sequence definitions are easy to get subtly wrong by hand.
--
-- From here the schema belongs to Flyway. ddl-auto is `validate` in prod, so an
-- entity change without a matching migration fails fast at startup instead of
-- silently altering a live database.

CREATE TABLE public.attachment (
    deleted boolean NOT NULL,
    comment_id bigint,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    size bigint NOT NULL,
    ticket_id bigint,
    uploader_user_id uuid,
    content_type character varying(255),
    filename character varying(255),
    data bytea
);
ALTER TABLE public.attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.comment (
    deleted boolean NOT NULL,
    internal boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    ticket_id bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    author_user_id uuid,
    content character varying(500) NOT NULL
);
ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.password_reset_token (
    used boolean NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    id uuid NOT NULL,
    user_user_id uuid NOT NULL,
    token character varying(255) NOT NULL
);
CREATE TABLE public.service_link_revision (
    id integer NOT NULL,
    "timestamp" bigint NOT NULL,
    actor_id uuid,
    actor_name character varying(255)
);
CREATE SEQUENCE public.service_link_revision_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
CREATE TABLE public.ticket (
    deleted boolean NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    assigned_to_user_id uuid,
    requester_user_id uuid,
    category character varying(255),
    description text,
    priority character varying(255),
    status character varying(255),
    title character varying(255),
    CONSTRAINT ticket_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT ticket_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'IN_PROGRESS'::character varying, 'ON_HOLD'::character varying, 'RESOLVED'::character varying, 'REOPENED'::character varying, 'CLOSED'::character varying])::text[])))
);
CREATE TABLE public.ticket_aud (
    rev integer NOT NULL,
    revtype smallint,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    assigned_to_user_id uuid,
    requester_user_id uuid,
    category character varying(255),
    description text,
    priority character varying(255),
    status character varying(255),
    title character varying(255),
    CONSTRAINT ticket_aud_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT ticket_aud_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'IN_PROGRESS'::character varying, 'ON_HOLD'::character varying, 'RESOLVED'::character varying, 'REOPENED'::character varying, 'CLOSED'::character varying])::text[])))
);
ALTER TABLE public.ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.user_table (
    deleted boolean NOT NULL,
    is_disabled boolean NOT NULL,
    user_id uuid NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT user_table_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'AGENT'::character varying, 'USER'::character varying])::text[])))
);
ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT attachment_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT password_reset_token_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT password_reset_token_token_key UNIQUE (token);
ALTER TABLE ONLY public.service_link_revision
    ADD CONSTRAINT service_link_revision_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ticket_aud
    ADD CONSTRAINT ticket_aud_pkey PRIMARY KEY (rev, id);
ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_table
    ADD CONSTRAINT user_table_email_key UNIQUE (email);
ALTER TABLE ONLY public.user_table
    ADD CONSTRAINT user_table_pkey PRIMARY KEY (user_id);
ALTER TABLE ONLY public.user_table
    ADD CONSTRAINT user_table_username_key UNIQUE (username);
ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fk6sfxekyphqe3c2dy6har5rerl FOREIGN KEY (author_user_id) REFERENCES public.user_table(user_id);
ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT fkds6u1rptrsif835t89kb15cyo FOREIGN KEY (comment_id) REFERENCES public.comment(id);
ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT fkedqxly6v2mkdjt67ujfn47qh9 FOREIGN KEY (ticket_id) REFERENCES public.ticket(id);
ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fki8ocmu7oaaqexurkq2sjpc3af FOREIGN KEY (requester_user_id) REFERENCES public.user_table(user_id);
ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fkj4xcb946kkl0dpn9or5a8fnp5 FOREIGN KEY (assigned_to_user_id) REFERENCES public.user_table(user_id);
ALTER TABLE ONLY public.ticket_aud
    ADD CONSTRAINT fkmqjfw9anjsrh1t1qu4rcyftc1 FOREIGN KEY (rev) REFERENCES public.service_link_revision(id);
ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT fko5nqdu6xyt36cjyd4x8o378x0 FOREIGN KEY (user_user_id) REFERENCES public.user_table(user_id);
ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT fkrw0d1y0eiwjkqyvevqbwh7w45 FOREIGN KEY (uploader_user_id) REFERENCES public.user_table(user_id);
ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fksyf8wt2qb7rhcau6v3p4axrba FOREIGN KEY (ticket_id) REFERENCES public.ticket(id);
